CREATE TABLE IF NOT EXISTS assets (
  id SERIAL PRIMARY KEY,
  symbol VARCHAR(10) UNIQUE NOT NULL,
  price NUMERIC(12,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  name VARCHAR(60) NOT NULL,
  balance NUMERIC(12,2) NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS holdings (
  id SERIAL PRIMARY KEY,
  user_id INT NOT NULL REFERENCES users(id),
  asset_id INT NOT NULL REFERENCES assets(id),
  qty INT NOT NULL DEFAULT 0,
  UNIQUE(user_id, asset_id)
);

CREATE TABLE IF NOT EXISTS categories (
  id SERIAL PRIMARY KEY,
  name VARCHAR(50) UNIQUE NOT NULL
);

ALTER TABLE assets
ADD COLUMN IF NOT EXISTS category_id INT NULL REFERENCES categories(id);


ALTER TABLE users
ADD COLUMN IF NOT EXISTS role VARCHAR(10) NOT NULL DEFAULT 'USER';

ALTER TABLE users
ADD COLUMN IF NOT EXISTS banned BOOLEAN NOT NULL DEFAULT FALSE;


CREATE TABLE IF NOT EXISTS trades (
  id SERIAL PRIMARY KEY,
  user_id INT NOT NULL REFERENCES users(id),
  asset_id INT NOT NULL REFERENCES assets(id),
  side VARCHAR(4) NOT NULL,  
  qty INT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);